# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: desenho.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'desenho.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdesenho.proto\x12\x07\x64\x65senho\"#\n\x11ReclamacaoRequest\x12\x0e\n\x06\x65vento\x18\x01 \x01(\t\"#\n\x12ReclamacaoResponse\x12\r\n\x05texto\x18\x01 \x01(\t2U\n\x0e\x44\x65senhoService\x12\x43\n\x08Reclamar\x12\x1a.desenho.ReclamacaoRequest\x1a\x1b.desenho.ReclamacaoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'desenho_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECLAMACAOREQUEST']._serialized_start=26
  _globals['_RECLAMACAOREQUEST']._serialized_end=61
  _globals['_RECLAMACAORESPONSE']._serialized_start=63
  _globals['_RECLAMACAORESPONSE']._serialized_end=98
  _globals['_DESENHOSERVICE']._serialized_start=100
  _globals['_DESENHOSERVICE']._serialized_end=185
# @@protoc_insertion_point(module_scope)
